language: node_js
node_js:
- '5'
env:
  global:
    secure: TyY1WicybZNbUyS1/NbKXKpeKRAHEi5k4xXblUN/vqbx5kQOpjk7ug/BzM4tscUdOrLlR/JRq9GvtMRbPY4jOU1MYmapfRyAE185Bobb8mk3wbxJckB9HJsR6Q32yk1Q6EUcPYZ8akKjXkZSu3dJgSYfHpjKMsmNweD08c+7Y2BrfN3zG5z5YMtS98eSUgSm45HKNpHIaIJv4c4jDHoHxCv5rbnyoQeuw0undgaS3TCzgLhA8Xdw0oVK2NdczIs5fL5A1NptJlh5yaeZqrmuIMVPVqjTLPectr1vvt5tug3LmvtAud+baSeVCHrpbCO0hsG3mcTL/WF3h/rwdBpS560wJJMF3V7ZlYraVWxXWf7bLyTCTpJijNqwlvI7iM6q/qcFcsJIw4H6JDKEHY8GFavBHt6ciweKJAArzpUYqEuQ4qxrGF9r+h9TxMaK4CgdgYq8QXAvVgrLpPP9qVXR13Mh6h/iZuhOXCtYBl91/+oMgaxjjnXKVwWckHrSSMh5dLeO3+I+49VYbeAJaQr+ScQTKa1MvO+egVtRWefujhEc7jcty2kG3Z7b2O8A/nYvHxFZQyMBKJ67lpNynH1+5Rcorv6T2uXhw7R0FzoBUfiF+Nt+s7Zj1cw5lYGk+x8ic9VI0iPMljLbnlewu04l2S/eWgVt4ABNEvQnwwznzdo=
