language: node_js
node_js:
- '5'
env:
  global:
    secure: Fatdp9FiHJcw4t+4WDRxKsTCIa6yNevgDY8RTRGQUdr1h7jugFHU2Qo/uAqEPtSF0XBFKRqLzdnWwn6HK79ZQfYkAklfF14jlPHvif7LjvBLxRSW4PdEk5xUccugCt1GrIeR481xM7LhZh0tFYd6EkI2HPgBymRspyTieFwW/pSY1P7LJftKNfZoA337+VV+PQGj7+oH23If+IZWr9cQqvK9zIBz2h3vKCFQEZibyrT2NpMAiAxmZmpPv1PdA58YCLr+kpHbGlceFY+nZ5hdZ99kjwepMgfKVlJNjk+vj0X8L/+AwjyDFfIrd9Aq6aGDVl9pUnPCBCrE/k+E4RJ3TZ09on9vooW/RwFVPhHKg5cAt42w2FtoDMluqi++UxDvqtVh3W7vhysHqexyzhEwuCe1vYYZcRrPXxG9IhIuP4ES516HuOUwzYRIng4TML6x8+rIUy1r/V+m5smo9pwuUk1m8iQsn2sGEVT0E+vAs0aOXzYWJJcCj1ErbmPwXq82FiGKwW5DSgbBthpWeM54Dm7qLttpw936N0PYlIUq9gYmW17MxDLFnww9MTiYUJW6GMVLz979/0EDPl/q+yxx8zNB5fQKjK/kbdSfJ07WAz7pR2nbNQZ3AU97y+Oa6U4Z9V/HnQULa/FXXLn+vJVnUE++NZl50UJNbe98EDlxbKU=
